[package]
name = "advent-of-code-2019"
version = "0.1.0"
authors = ["Brandon Williams <bwilliams.eng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
anyhow = "1.0"
itertools = "0.8"
